version: "3.9"

services:
  temporal:
    image: temporalio/auto-setup:1.24.0
    container_name: temporal
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PWD=admin
      - POSTGRES_SEEDS=db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    ports:
      - "7233:7233"   
    depends_on:
      - db

  temporal-ui:
    image: temporalio/ui:2.31.2
    container_name: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8000
    ports:
      - "8233:8080"   
    depends_on:
      - temporal

  db:
    image: postgres:15
    container_name: temporal-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=orders
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal -d orders"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data: